name: jaguar_generator
description: Generator for Jaguar
version: 0.1.10
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

dependencies:
  source_gen: ">=0.5.1+3 <0.6.0"
  build: ">=0.4.1 <0.5.0"
  yaml: ">=2.1.10 <3.0.0"
  jaguar: ">=0.1.0 <0.2.0"
    # path: ../jaguar
    # git: https://github.com/Jaguar-dart/jaguar.git
  source_gen_help:
    git:
      url: https://github.com/Jaguar-dart/source_gen_help.git
      ref: 4acd8b6

dev_dependencies:
  test: 0.12.15+10
