name: jaguar_generator
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

dependencies:
  source_gen: ">=0.5.1+3 <0.6.0"
  build: ">=0.4.1 <0.5.0"
  yaml: ">=2.1.10 <3.0.0"
  jaguar:
    # path: ../jaguar
    git: https://github.com/Jaguar-dart/jaguar.git
  source_gen_help:
    # path: ../source_gen_help
    git: https://github.com/Jaguar-dart/source_gen_help.git

dev_dependencies:
  test: 0.12.15+10
